version: '3.8'

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    restart: unless-stopped
    volumes:
      - ./user_data:/freqtrade/user_data
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freqtrade.rule=Host(`freqtrade.rainomotion.com`)"
      - "traefik.http.routers.freqtrade.entrypoints=https"
      - "traefik.http.routers.freqtrade.tls=true"
      - "traefik.http.routers.freqtrade.tls.certresolver=letsencrypt"
      - "traefik.http.services.freqtrade.loadbalancer.server.port=8080"
      - "traefik.http.routers.freqtrade.middlewares=gzip"

networks:
  default:
    external: true
    name: coolify
